"""
utils/email_report.py
---------------------
Builds an HTML weekly-report string and (optionally) sends it via SMTP.

For a weekend project, SMTP credentials are read from Streamlit secrets or
environment variables so nothing sensitive lives in source code.

If no SMTP config is present the function returns the HTML string so the
caller can display a preview instead of crashing.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

import pandas as pd


# ── HTML template ─────────────────────────────────────────────────────────

def _build_html(df: pd.DataFrame, summary: str, question: str) -> str:
    table_rows = ""
    for _, row in df.iterrows():
        cells = "".join(f"<td style='padding:6px 12px;border-bottom:1px solid #e5e7eb'>{v}</td>" for v in row)
        table_rows += f"<tr>{cells}</tr>"

    headers = "".join(
        f"<th style='padding:8px 12px;background:#6366F1;color:#fff;text-align:left'>{c}</th>"
        for c in df.columns
    )

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Inter,Arial,sans-serif;background:#f9fafb;padding:24px">
  <div style="max-width:700px;margin:auto;background:#fff;border-radius:12px;
              box-shadow:0 2px 8px rgba(0,0,0,.08);overflow:hidden">

    <div style="background:#6366F1;padding:28px 32px">
      <h1 style="color:#fff;margin:0;font-size:22px">📊 Weekly Sales Report</h1>
      <p style="color:#e0e7ff;margin:6px 0 0">{datetime.today().strftime('%B %d, %Y')}</p>
    </div>

    <div style="padding:28px 32px">
      <h2 style="font-size:15px;color:#374151;margin-top:0">Query</h2>
      <p style="background:#f3f4f6;border-radius:8px;padding:12px 16px;
                font-style:italic;color:#4b5563">{question}</p>

      <h2 style="font-size:15px;color:#374151">AI Summary</h2>
      <p style="color:#374151;line-height:1.7">{summary}</p>

      <h2 style="font-size:15px;color:#374151">Data</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead><tr>{headers}</tr></thead>
        <tbody>{table_rows}</tbody>
      </table>
    </div>

    <div style="background:#f9fafb;padding:16px 32px;
                border-top:1px solid #e5e7eb;text-align:center">
      <p style="color:#9ca3af;font-size:12px;margin:0">
        Generated by AI Reporting Agent · {datetime.today().strftime('%Y-%m-%d %H:%M')}
      </p>
    </div>
  </div>
</body>
</html>
"""


# ── Send or return ────────────────────────────────────────────────────────

def send_email_report(
    df: pd.DataFrame,
    summary: str,
    question: str,
    to_address: str,
) -> dict:
    """
    Tries to send the HTML report via SMTP.

    Reads config from environment variables:
        SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM

    Returns
    -------
    dict with keys:
        sent    : bool
        html    : the HTML string (always returned for preview)
        message : human-readable status
    """
    html = _build_html(df, summary, question)

    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    from_addr = os.getenv("SMTP_FROM", smtp_user or "noreply@example.com")

    if not all([smtp_host, smtp_user, smtp_pass, to_address]):
        return {
            "sent": False,
            "html": html,
            "message": "SMTP not configured — showing preview below.",
        }

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Weekly Sales Report — {datetime.today().strftime('%b %d, %Y')}"
        msg["From"]    = from_addr
        msg["To"]      = to_address
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, [to_address], msg.as_string())

        return {"sent": True, "html": html, "message": f"Report sent to {to_address} ✅"}

    except Exception as exc:
        return {"sent": False, "html": html, "message": f"Send failed: {exc}"}
